name: Build and publish release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - name: Install dependencies
        run: bun install

      - name: Build for x64 (modern)
        run: |
          bun build --compile --target=bun-linux-x64-modern --minify --sourcemap --bytecode src/server.js --outfile ping-trace-api-linux-x64-modern

      - name: Build for x64 (baseline)
        run: |
          bun build --compile --target=bun-linux-x64-baseline --minify --sourcemap --bytecode src/server.js --outfile ping-trace-api-linux-x64-baseline

      - name: Build for arm64
        run: |
          bun build --compile --target=bun-linux-arm64 --minify --sourcemap --bytecode src/server.js --outfile ping-trace-api-linux-arm64

      - name: Create Release and Upload Assets
        id: gh_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ping-trace-api-linux-x64-modern
            ping-trace-api-linux-x64-baseline
            ping-trace-api-linux-arm64
